from app.schemas import InventoryItem

PROGRAM_ID = "interview_bootcamp_v1"

QUESTION_INVENTORY = [
    InventoryItem(
        id="q.self_intro.1",
        item_type="QUESTION",
        family="SELF_INTRODUCTION",
        content="Tell me about yourself.",
        tags=["introduction"],
    ),
    InventoryItem(
        id="q.career_transition.1",
        item_type="QUESTION",
        family="CAREER_TRANSITION",
        content="Why are you moving into this field?",
        tags=["motivation"],
    ),
    InventoryItem(
        id="q.why_ai.1",
        item_type="QUESTION",
        family="WHY_AI",
        content="Why are you interested in AI?",
        tags=["motivation"],
    ),
    InventoryItem(
        id="q.why_role.1",
        item_type="QUESTION",
        family="WHY_THIS_ROLE",
        content="Why does this role interest you?",
        tags=["motivation"],
    ),
    InventoryItem(
        id="q.why_company.1",
        item_type="QUESTION",
        family="WHY_THIS_COMPANY",
        content="Why this company?",
        tags=["motivation"],
    ),
    InventoryItem(
        id="q.experience.1",
        item_type="QUESTION",
        family="RELEVANT_EXPERIENCE",
        content="What previous experience prepares you for this role?",
        tags=["experience"],
    ),
    InventoryItem(
        id="q.project.1",
        item_type="QUESTION",
        family="PROJECT_EXPERIENCE",
        content="Tell me about a project you are proud of.",
        tags=["story"],
    ),
    InventoryItem(
        id="q.strength.1",
        item_type="QUESTION",
        family="STRENGTHS",
        content="What is one of your strengths?",
        tags=["reflection"],
    ),
    InventoryItem(
        id="q.weakness.1",
        item_type="QUESTION",
        family="WEAKNESSES",
        content="What is a weakness you are working on?",
        tags=["reflection"],
    ),
    InventoryItem(
        id="q.achievement.1",
        item_type="QUESTION",
        family="ACHIEVEMENT",
        content="Describe an achievement that matters to you.",
        tags=["story"],
    ),
    InventoryItem(
        id="q.challenge.1",
        item_type="QUESTION",
        family="CHALLENGE",
        content="Tell me about a difficult challenge.",
        tags=["story"],
    ),
    InventoryItem(
        id="q.failure.1",
        item_type="QUESTION",
        family="FAILURE",
        content="Tell me about a failure and what you learned.",
        tags=["story"],
    ),
    InventoryItem(
        id="q.collaboration.1",
        item_type="QUESTION",
        family="COLLABORATION",
        content="How do you work with others?",
        tags=["story"],
    ),
    InventoryItem(
        id="q.conflict.1",
        item_type="QUESTION",
        family="CONFLICT",
        content="Describe a conflict you helped resolve.",
        tags=["story"],
    ),
    InventoryItem(
        id="q.problem_solving.1",
        item_type="QUESTION",
        family="PROBLEM_SOLVING",
        content="How do you approach an ambiguous problem?",
        tags=["story"],
    ),
    InventoryItem(
        id="q.learning.1",
        item_type="QUESTION",
        family="LEARNING_QUICKLY",
        content="How do you learn something new quickly?",
        tags=["story"],
    ),
    InventoryItem(
        id="q.initiative.1",
        item_type="QUESTION",
        family="INITIATIVE",
        content="Tell me about a time you took initiative.",
        tags=["story"],
    ),
    InventoryItem(
        id="q.future.1",
        item_type="QUESTION",
        family="FUTURE_PLANS",
        content="Where do you want to grow next?",
        tags=["future"],
    ),
]

LANGUAGE_INVENTORY = [
    InventoryItem(
        id="lang.transition_into",
        item_type="LANGUAGE",
        family="CHUNK",
        content="transition into the AI industry",
        tags=["career_transition"],
    ),
    InventoryItem(
        id="lang.rapidly_evolving",
        item_type="LANGUAGE",
        family="CHUNK",
        content="a rapidly evolving field",
        tags=["motivation"],
    ),
    InventoryItem(
        id="lang.naturally_curious",
        item_type="LANGUAGE",
        family="CHUNK",
        content="I am naturally curious about…",
        tags=["motivation"],
    ),
    InventoryItem(
        id="lang.transferable",
        item_type="LANGUAGE",
        family="CHUNK",
        content="highly transferable",
        tags=["experience"],
    ),
    InventoryItem(
        id="lang.strong_fit",
        item_type="LANGUAGE",
        family="SENTENCE_FRAME",
        content="What makes me a strong fit is…",
        tags=["experience"],
    ),
    InventoryItem(
        id="lang.star",
        item_type="LANGUAGE",
        family="DISCOURSE_STRUCTURE",
        content="situation, task, action, result",
        tags=["story"],
    ),
    InventoryItem(
        id="lang.thinking_time",
        item_type="LANGUAGE",
        family="FUNCTIONAL_LANGUAGE",
        content="Let me take a moment to think about that.",
        tags=["clarification"],
    ),
]

STRATEGY_INVENTORY = [
    InventoryItem(
        id="strategy.self_intro",
        item_type="STRATEGY",
        family="SELF_INTRODUCTION",
        content="present → relevant background → direction",
        tags=["introduction"],
    ),
    InventoryItem(
        id="strategy.star",
        item_type="STRATEGY",
        family="STAR",
        content="situation → task → action → result",
        tags=["story"],
    ),
    InventoryItem(
        id="strategy.career_transition",
        item_type="STRATEGY",
        family="CAREER_TRANSITION",
        content="past strength → motivation → transferable fit",
        tags=["motivation"],
    ),
    InventoryItem(
        id="strategy.why_role",
        item_type="STRATEGY",
        family="WHY_THIS_ROLE",
        content="role fit → evidence → growth direction",
        tags=["motivation"],
    ),
    InventoryItem(
        id="strategy.clarify",
        item_type="STRATEGY",
        family="CLARIFICATION",
        content="clarify → think → answer",
        tags=["clarification"],
    ),
    InventoryItem(
        id="strategy.follow_up",
        item_type="STRATEGY",
        family="FOLLOW_UP",
        content="answer directly → give evidence → reflect",
        tags=["follow_up"],
    ),
]

STORY_CATEGORIES = (
    "ACHIEVEMENT",
    "CHALLENGE",
    "FAILURE",
    "CONFLICT",
    "COLLABORATION",
    "LEADERSHIP",
    "PROBLEM_SOLVING",
    "LEARNING_QUICKLY",
    "INITIATIVE",
    "AMBIGUITY",
    "COMMUNICATION",
    "TECHNICAL_CHALLENGE",
    "CAREER_TRANSITION",
)
